version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/sports
      - REDIS_URL=redis://redis:6379
      - SPORTMONKS_TOKEN=SGOwv7vqpd5vWfjM1KVH8vnICMSNBivrBmlMJA7xFq51TTN5ttYqcD82XZns
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"